name: CI devops 2021 EPF 
on: 
  #to begin you want to launch this job in main and develop 
  push: 
    branches: master 
  pull_request: 
jobs: 
  build-and-test-app : 
    runs-on: ubuntu-18.04 
    steps: 
    #checkout your github code using actions/checkout@v2.3.3
    - uses: actions/checkout@v2.3.3 
    #do the same with another action (actions/setup-java@v2) that enable to setup jdk 11    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: 'adopt'
    #finally build your app with the latest command 
    - name: Build and test with Maven 
      env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    # run: mvn clean verify --file ./simple-api/pom.xml
      run: mvn -B verify sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=hansfrancois -Dsonar.projectKey=hansfrancois_tp2 --file ./simple-api/pom.xml
        
  # define job to build and publish docker image 
  build-and-push-docker-image: 
    needs: build-and-test-app
  # run only when code is compiling and tests are passing 
    runs-on: ubuntu-latest 
  # steps to perform in job 
    steps: 
    - name: Checkout code 
      uses: actions/checkout@v2.3.3 
    - name: Login to DockerHub 
      run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_TOKEN }}
    - name: Build image and push backend 
      uses: docker/build-push-action@v2 
      with: 
        # relative path to the place where source code with Dockerfile is located 
        context: ./simple-api
        # Note: tags has to be all lower-case 
        tags: ${{secrets.DOCKER_HUB_USERNAME}}/tp-devops-epf:simple-api 
        # build on feature branches, push only on main branch 
        push: ${{ github.ref == 'refs/heads/master' }}
    - name: Build image and push database 
      uses: docker/build-push-action@v2 
      with: 
        # relative path to the place where source code with Dockerfile is located 
        context: ./database
        # Note: tags has to be all lower-case 
        tags: ${{secrets.DOCKER_HUB_USERNAME}}/tp-devops-epf:database
        # build on feature branches, push only on main branch 
        push: ${{ github.ref == 'refs/heads/master' }}
    # DO the same for httpd 
    - name: Build image and push httpd
      uses: docker/build-push-action@v2 
      with: 
        # relative path to the place where source code with Dockerfile is located 
        context: ./httpd
        # Note: tags has to be all lower-case 
        tags: ${{secrets.DOCKER_HUB_USERNAME}}/tp-devops-epf:httpd
        # build on feature branches, push only on main branch 
        push: ${{ github.ref == 'refs/heads/master' }}
    # DO the same for front 
    - name: Build image and push front
      uses: docker/build-push-action@v2 
      with: 
        # relative path to the place where source code with Dockerfile is located 
        context: ./devops-front
        # Note: tags has to be all lower-case 
        tags: ${{secrets.DOCKER_HUB_USERNAME}}/tp-devops-epf:devops-front
        # build on feature branches, push only on main branch 
        push: ${{ github.ref == 'refs/heads/master' }}
    
