name: CI devops 2021 EPF 
on: 
  #to begin you want to launch this job in main and develop 
  push: 
    branches: master 
  pull_request: 
jobs: 
  build-and-test-app : 
    runs-on: ubuntu-18.04 
    steps: 
    #checkout your github code using actions/checkout@v2.3.3
    - uses: actions/checkout@v2.3.3 
    #do the same with another action (actions/setup-java@v2) that enable to setup jdk 11    
    - name: Set up JDK 11
      uses: actions/setup-java@v2.3.1
      with:
        java-version: 2.3.1
        distribution: 11
             
    #finally build your app with the latest command 
    - name: Build and test with Maven 
      run: mvn clean verify --file ./simple-api/pom.xml
